__version__ = "0.1.5"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = u'develop'
__git_remote_tracking_branch__ = u'origin/develop'
__git_remote_url__ = u'https://github.com/Infinidat/infi.srm_client.git'
__git_head_hash__ = '6f8c16328bffe85c8328aa1b6d84b2bf602203cf'
__git_head_subject__ = u'fixing _extract_protected_vm'
__git_head_message__ = u''
__git_dirty_diff__ = u''